# 01. Intro - Homework 

Link for exercises

https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/cohorts/2024/01-intro/homework.md

In [2]:
import pandas as pd
import numpy as np

In [3]:
# 1. Current pandas version
pd.__version__

'2.0.3'

In [4]:
# Get data
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

In [8]:
# Q2. Records Count
df.shape

(2160, 12)

In [18]:
# Q3. Laptop brands
df.Brand.value_counts()

Brand
Asus                415
HP                  368
Lenovo              366
MSI                 308
Acer                137
Apple               116
Dell                 84
Microsoft            77
Gigabyte             48
Razer                37
Medion               32
LG                   32
Alurin               29
PcCom                24
Samsung              22
Dynabook Toshiba     19
Vant                 11
Primux                8
Deep Gaming           8
Innjoo                6
Thomson               4
Prixton               3
Millenium             2
Denver                1
Jetwing               1
Realme                1
Toshiba               1
Name: count, dtype: int64

In [19]:
df.Brand.nunique()

27

In [20]:
# Q4. Missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [25]:
# Q5. Maximum final price
dell = df[(df.Brand=="Dell")]
dell["Final Price"].max()

3936.0

In [40]:
# Q6. Median value of Screen
#    Find the median value of Screen column in the dataset.
#    Next, calculate the most frequent value of the same Screen column.
#    Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
#    Now, calculate the median value of Screen once again.
df.Screen.median()

15.6

In [41]:
mode = df.Screen.mode()[0]
mode

15.6

In [42]:
df.Screen = df.Screen.fillna(mode)

In [43]:
df.Screen.median()

15.6

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2160 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [46]:
# Q7
innjoo = df[(df.Brand == "Innjoo")]
innjoo_selected = innjoo[["RAM", "Storage", "Screen"]]
innjoo_selected

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [79]:
X = np.array(innjoo_selected)
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [80]:
XTX = X.T.dot(X)

In [81]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [82]:
np.linalg.det(XTX)

611414507.5199898

In [83]:
inver = np.linalg.inv(XTX)
inver

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [84]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [85]:
inver_T = inver.dot(X.T)
inver_T

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [86]:
w = inver_T.dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [88]:
sum(w)

91.29988062995588